name: FR
version: 2.4.1
date: 09/02/2017
description: Computations with functionally recursive groups

authors:
    - name: Laurent Bartholdi
      url: http://www.uni-math.gwdg.de/laurent

maintainers:
    - name: Laurent Bartholdi
      url: http://www.uni-math.gwdg.de/laurent

GAP: ">=4.8"

needed-pkgs:
    - name: "FGA"
      version: ">=1.1"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/FGA/"
    - name: "Polycyclic"
      version: ">=2.2"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/polycyclic/"
    - name: "GAPDoc"
      version: ">=1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

suggested-pkgs:
    - name: "GBNP"
      version: ">=0.9"
      url: "http://mathdox.org/products/gbnp/"
    - name: "NQ"
      version: ">=2.4"
      url: "http://gap-packages.github.io/nq/"
    - name: "LPRES"
      version: ">=0.1"
      url: "https://gap-packages.github.io/lpres"

www: https://gap-packages.github.io/fr
readme: https://gap-packages.github.io/fr/README
packageinfo: https://gap-packages.github.io/fr/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/fr/releases/download/v2.4.1/fr-2.4.1.tar.gz

abstract: The <span class="pkgname">fr</span> package allows    GAP to manipulate groups generated by automata, and more generally    functionally recursive groups

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
