name: FR
version: "2.4.13"
license: "GPL-2.0-or-later"
date: 2024-01-11
description: |
    Computations with functionally recursive groups

authors:
    - name: Laurent Bartholdi
      url: https://www.math.uni-sb.de/ag/bartholdi/

maintainers:
    - name: Laurent Bartholdi
      url: https://www.math.uni-sb.de/ag/bartholdi/

GAP: ">=4.8"

needed-pkgs:
    - name: "FGA"
      version: ">=1.1"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/FGA/"
    - name: "IO"
      version: ">=4.0"
      url: "https://gap-packages.github.io/io"
    - name: "Polycyclic"
      version: ">=2.2"
      url: "https://gap-packages.github.io/polycyclic/"
    - name: "GAPDoc"
      version: ">=1.0"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

suggested-pkgs:
    - name: "GBNP"
      version: ">=0.9"
      url: "https://gap-packages.github.io/gbnp/"
    - name: "NQ"
      version: ">=2.4"
      url: "https://gap-packages.github.io/nq/"
    - name: "LPRES"
      version: ">=0.1"
      url: "https://gap-packages.github.io/lpres"

www: https://gap-packages.github.io/fr
readme: README.md
packageinfo: https://gap-packages.github.io/fr/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/fr/releases/download/v2.4.13/fr-2.4.13.tar.gz

abstract: |
    The <span class="pkgname">fr</span> package allows    GAP to manipulate groups generated by automata, and more generally    functionally recursive groups

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    functionally recursive group, mealy machine, automata group.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Bar24</span>]   <b class='BibAuthor'>Bartholdi, L.</b>,
     <i class='BibTitle'>FR, Computations with functionally recursive groups,
             Version 2.4.13</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/fr">https://gap-packages.github.io/fr</a></span>.
    </p>
    

bibtex: |
    @misc{ FR2.4.13,
      author =           {Bartholdi, L.},
      title =            {{FR}, Computations with functionally recursive groups,
                          {V}ersion 2.4.13},
      month =            {Jan},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href              {https://gap-packages.github.io/fr}
                          {\texttt{https://gap-packages.github.io/fr}}},
      keywords =         {functionally  recursive group; mealy machine; automata
                          group},
      printedkey =       {Bar24}
    }

